import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 24, fontWeight: 700 },
  row: {
    flexDirection: "row",
    marginBottom: 10,
    borderBottom: "1 solid #E7E2D6",
    paddingBottom: 6,
  },
  label: { width: 180, color: "#6b7280" },
  value: { flex: 1 },
  footer: { marginTop: 30, fontSize: 9, color: "#9ca3af" },
});

export interface CompanyApplicationDocumentProps {
  companyName: string;
  businessName: string;
  licenseNumber: string;
  businessAddress: string;
  registrationJurisdiction: string;
  phone: string;
  isoCertification?: string;
  submittedAt: string;
}

export function CompanyApplicationDocument({
  companyName,
  businessName,
  licenseNumber,
  businessAddress,
  registrationJurisdiction,
  phone,
  isoCertification,
  submittedAt,
}: CompanyApplicationDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Company Verification Application</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Platform company name</Text>
          <Text style={styles.value}>{companyName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Legal business name</Text>
          <Text style={styles.value}>{businessName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>License / registration number</Text>
          <Text style={styles.value}>{licenseNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Business address</Text>
          <Text style={styles.value}>{businessAddress}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Registration jurisdiction</Text>
          <Text style={styles.value}>{registrationJurisdiction}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Phone</Text>
          <Text style={styles.value}>{phone}</Text>
        </View>
        {isoCertification && (
          <View style={styles.row}>
            <Text style={styles.label}>ISO certification</Text>
            <Text style={styles.value}>{isoCertification}</Text>
          </View>
        )}

        <Text style={styles.footer}>
          Generated by AlcheMatch on {submittedAt}. This document was generated from
          applicant-submitted form data and has not been independently verified.
        </Text>
      </Page>
    </Document>
  );
}